import React, { useState, useRef } from 'react';
import { Icons } from './components/Icon';
import { SettingsPanel } from './components/SettingsPanel';
import { PlatformCard } from './components/PlatformCard';
import { Settings, GenerationState, ImageSize, AspectRatio, Platform } from './types';
import { generateSocialContent, generateImageForPlatform, generateSinglePlatformText } from './services/geminiService';

const App: React.FC = () => {
  const [idea, setIdea] = useState('');
  const [settings, setSettings] = useState<Settings>({
    tone: 'Professional',
    imageSize: ImageSize.Size1K,
    aspectRatio: AspectRatio.Auto,
    textLength: 'Medium'
  });

  const [state, setState] = useState<GenerationState>({
    isGeneratingText: false,
    isGeneratingImages: false
  });

  // Track specific loading states for individual regenerations
  const [regenerating, setRegenerating] = useState<Record<string, boolean>>({});

  const resultsRef = useRef<HTMLDivElement>(null);

  const handleSettingsUpdate = (newSettings: Partial<Settings>) => {
    setSettings(prev => ({ ...prev, ...newSettings }));
  };

  const setPlatformRegenerating = (platform: Platform, type: 'text' | 'image', isLoading: boolean) => {
    setRegenerating(prev => ({
      ...prev,
      [`${platform}-${type}`]: isLoading
    }));
  };

  const isPlatformRegenerating = (platform: Platform, type: 'text' | 'image') => {
    return !!regenerating[`${platform}-${type}`];
  };

  const handleGenerate = async () => {
    if (!idea.trim()) return;

    setState({
      isGeneratingText: true,
      isGeneratingImages: true,
      error: undefined,
      content: undefined,
      images: undefined
    });
    setRegenerating({}); // Reset granular states

    try {
      // 1. Generate Text
      const content = await generateSocialContent(idea, settings.tone, settings.textLength);
      
      setState(prev => ({
        ...prev,
        isGeneratingText: false,
        content: content
      }));

      // Scroll to results if needed
      setTimeout(() => {
        resultsRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 100);

      // 2. Generate Images in Parallel
      const platforms = ['linkedin', 'twitter', 'instagram', 'pinterest', 'youtube', 'discord'] as const;
      
      const imagePromises = platforms.map(async (platform) => {
        try {
          // Use the specific prompt generated by the text model
          const prompt = content[platform].imagePrompt;
          const base64 = await generateImageForPlatform(platform, prompt, settings.tone, {
            size: settings.imageSize,
            aspectRatio: settings.aspectRatio
          });
          return { platform, base64 };
        } catch (error: any) {
          console.error(`Failed to generate image for ${platform}`, error);
          return { platform, base64: null };
        }
      });

      const results = await Promise.all(imagePromises);
      
      const newImages: any = {};
      results.forEach(res => {
        if (res.base64) newImages[res.platform] = res.base64;
      });

      setState(prev => ({
        ...prev,
        isGeneratingImages: false,
        images: newImages
      }));

      // If all images failed, set error
      if (results.every(r => r.base64 === null)) {
         setState(prev => ({
           ...prev,
           error: "Text generated, but images failed. The free tier quota might be exhausted."
         }));
      }

    } catch (error: any) {
      console.error("Generation failed", error);
      
      setState(prev => ({
        ...prev,
        isGeneratingText: false,
        isGeneratingImages: false,
        error: error.message || "Failed to generate content. Please try again."
      }));
    }
  };

  const handleRegenerateText = async (platform: Platform) => {
    if (!idea) return;
    setPlatformRegenerating(platform, 'text', true);

    try {
      const newPost = await generateSinglePlatformText(platform, idea, settings.tone, settings.textLength);
      
      setState(prev => {
        if (!prev.content) return prev;
        return {
          ...prev,
          content: {
            ...prev.content,
            [platform]: newPost
          }
        };
      });
    } catch (error) {
      console.error(`Failed to regenerate text for ${platform}`, error);
    } finally {
      setPlatformRegenerating(platform, 'text', false);
    }
  };

  const handleRegenerateImage = async (platform: Platform) => {
    const post = state.content?.[platform];
    if (!post) return;
    
    setPlatformRegenerating(platform, 'image', true);

    try {
      const base64 = await generateImageForPlatform(platform, post.imagePrompt, settings.tone, {
        size: settings.imageSize,
        aspectRatio: settings.aspectRatio
      });

      setState(prev => ({
        ...prev,
        images: {
          ...prev.images,
          [platform]: base64
        }
      }));
    } catch (error) {
       console.error(`Failed to regenerate image for ${platform}`, error);
    } finally {
      setPlatformRegenerating(platform, 'image', false);
    }
  };

  const platforms: Platform[] = ['linkedin', 'twitter', 'instagram', 'pinterest', 'youtube', 'discord'];

  return (
    <div className="min-h-screen bg-neutral-950 text-white font-sans selection:bg-orange-500/30 selection:text-orange-100">
      
      {/* Header */}
      <header className="border-b border-neutral-800 bg-neutral-950/80 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-500 to-red-600 flex items-center justify-center shadow-lg shadow-orange-900/20">
              <Icons.Zap className="w-5 h-5 text-white" />
            </div>
            <h1 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-orange-400 to-red-400">
              Social Forge
            </h1>
          </div>
          <div className="flex items-center gap-4 text-sm text-neutral-400">
             <span className="hidden md:inline-flex items-center gap-1">
                <Icons.Sparkles className="w-3 h-3 text-orange-500" />
                Powered by Gemini
             </span>
          </div>
        </div>
      </header>

      <main className="max-w-7xl mx-auto px-4 py-8 md:py-12">
        
        {/* Input Section */}
        <div className="max-w-3xl mx-auto mb-16">
          <div className="text-center mb-8">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
              Forge Your Social Presence
            </h2>
            <p className="text-neutral-400 text-lg">
              Turn a single idea into tailored posts and visuals for every platform instantly.
            </p>
          </div>

          <div className="bg-neutral-900 rounded-2xl p-2 shadow-2xl shadow-black border border-neutral-800">
            <div className="relative">
              <textarea
                value={idea}
                onChange={(e) => setIdea(e.target.value)}
                placeholder="What's your big idea? e.g., 'Launching a new eco-friendly coffee mug made from recycled bamboo...'"
                className="w-full bg-neutral-950 text-white p-6 rounded-xl border border-neutral-800 focus:border-orange-500 focus:ring-1 focus:ring-orange-500 outline-none resize-none min-h-[140px] text-lg placeholder:text-neutral-600 transition-all"
                disabled={state.isGeneratingText}
              />
              <div className="absolute bottom-4 right-4 text-xs text-neutral-600">
                {idea.length} chars
              </div>
            </div>
            
            <div className="p-2">
               <SettingsPanel 
                 settings={settings} 
                 onUpdate={handleSettingsUpdate} 
                 disabled={state.isGeneratingText} 
               />

               <button
                 onClick={handleGenerate}
                 disabled={!idea.trim() || state.isGeneratingText}
                 className="w-full bg-gradient-to-r from-orange-600 to-red-600 hover:from-orange-500 hover:to-red-500 disabled:from-neutral-800 disabled:to-neutral-900 disabled:text-neutral-500 disabled:cursor-not-allowed text-white font-bold py-4 rounded-xl shadow-lg transition-all transform active:scale-[0.99] flex items-center justify-center gap-2 text-lg border border-white/5"
               >
                 {state.isGeneratingText ? (
                   <>
                     <Icons.Loader2 className="w-5 h-5 animate-spin" />
                     Forging Content...
                   </>
                 ) : (
                   <>
                     <Icons.Sparkles className="w-5 h-5" />
                     Generate Campaign
                   </>
                 )}
               </button>
            </div>
          </div>
          
          {state.error && (
            <div className="mt-4 p-4 bg-red-950/30 border border-red-900/50 rounded-xl text-red-400 text-center text-sm">
              {state.error}
            </div>
          )}
        </div>

        {/* Results Grid */}
        <div ref={resultsRef} className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {(state.content || state.isGeneratingText) && (
            <>
              {platforms.map(platform => (
                 <PlatformCard
                   key={platform}
                   platform={platform}
                   data={state.content?.[platform]}
                   image={state.images?.[platform]}
                   isLoadingText={state.isGeneratingText || isPlatformRegenerating(platform, 'text')}
                   isLoadingImage={state.isGeneratingImages || isPlatformRegenerating(platform, 'image')}
                   onRegenerateText={() => handleRegenerateText(platform)}
                   onRegenerateImage={() => handleRegenerateImage(platform)}
                 />
              ))}
            </>
          )}
        </div>
        
        {/* Empty State / Welcome Graphics */}
        {!state.content && !state.isGeneratingText && (
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 opacity-20 pointer-events-none grayscale select-none">
             {/* Placeholders to show layout structure before generation */}
             {platforms.map(p => (
                <div key={p} className="h-64 border border-neutral-800 rounded-2xl bg-neutral-900 flex items-center justify-center">
                   <Icons.Sparkles className="w-8 h-8 text-neutral-600" />
                </div>
             ))}
          </div>
        )}

      </main>
    </div>
  );
};

export default App;